/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Produto;
import listener.ProcurarProdutoListener;

/**
 *
 * @author gustavo
 */
public class ProcurarProdutoJIF extends javax.swing.JInternalFrame {
    
    private ProcurarProdutoListener listener;
    
    private Produto produto;
    private String auxReferencia;
    private String[] listReferencias;
    
    public void apagarCampos(){
	campoReferencia.setText("");
	listaReferencias.removeAll();
    }
    
    public String getReferencia(){
	String selection = "Vazio";
	if(listaReferencias.getMaxSelectionIndex() > -1){
	    selection = listaReferencias.getSelectedValue().toString();
	}
	
	return (selection);
    }
    
    public void ProcurarReferencia(){
	listaReferencias.removeAll();
	
	auxReferencia = campoReferencia.getText();
	for (int i = 0; i < 10; i++) {
	    if(produto.getReferencia().contains(auxReferencia)){
		listReferencias[i] = produto.getReferencia();
	    }
	}
	
	listaReferencias.setListData(listReferencias);
    }

    /**
     * Creates new form ProcurarProduto
     */
    public ProcurarProdutoJIF() {
	listener = new ProcurarProdutoListener(this);
	
        initComponents();
	
	campoReferencia.setActionCommand("campoReferencia");
	copiarProcurarProduto.setActionCommand("copiarProcurarProduto");
	cancelarProcurarProduto.setActionCommand("cancelarProcurarProduto");
	campoReferencia.addActionListener(listener);
	copiarProcurarProduto.addActionListener(listener);
	cancelarProcurarProduto.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelReferencia = new javax.swing.JLabel();
        campoReferencia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaReferencias = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        copiarProcurarProduto = new javax.swing.JButton();
        cancelarProcurarProduto = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        labelReferencia.setText("Referência :");

        jScrollPane1.setViewportView(listaReferencias);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Procurar Produto");

        copiarProcurarProduto.setText("Copiar");
        copiarProcurarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiarProcurarProdutoActionPerformed(evt);
            }
        });

        cancelarProcurarProduto.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(copiarProcurarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cancelarProcurarProduto)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelReferencia)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelReferencia)
                    .addComponent(campoReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(copiarProcurarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelarProcurarProduto)))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void copiarProcurarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiarProcurarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_copiarProcurarProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoReferencia;
    private javax.swing.JButton cancelarProcurarProduto;
    private javax.swing.JButton copiarProcurarProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelReferencia;
    private javax.swing.JList listaReferencias;
    // End of variables declaration//GEN-END:variables
}
