/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import listener.RelatorioListener;

/**
 *
 * @author juanvmr
 */
public class RelatorioJIF extends javax.swing.JInternalFrame {
    
    private RelatorioListener listener;

    /**
     * Creates new form RelatorioJIF
     */
    public RelatorioJIF() {
        initComponents();
        
        listener = new RelatorioListener(this);
        
        botaoFechar.setActionCommand("fecharRelatorio");
        botaoLimpar.setActionCommand("limparRelatorio");
        
        botaoFechar.addActionListener(listener);
        botaoLimpar.addActionListener(listener);
        
        if(campoRelatorio.getLineWrap()){
            campoRelatorio.setLineWrap(false);
        }
    }
    
    public void apagarCampos(){
        campoRelatorio.setText("");
    }
    
    public void gerarRelatorio(String texto){
        campoRelatorio.setText(texto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoFechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoRelatorio = new javax.swing.JTextArea();
        botaoLimpar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(640, 480));

        botaoFechar.setText("Fechar");

        campoRelatorio.setColumns(20);
        campoRelatorio.setRows(5);
        jScrollPane1.setViewportView(campoRelatorio);

        botaoLimpar.setText("Limpar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoFechar)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoFechar)
                    .addComponent(botaoLimpar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoFechar;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JTextArea campoRelatorio;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
